/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exam;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        ER = new javax.swing.JLabel();
        Users = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        ME = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("Hello!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 70, 60, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 160, 210, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        jLabel3.setText("ADMIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 80, 150, 90);

        ER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/EXAM RESULT.png"))); // NOI18N
        ER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ERMouseClicked(evt);
            }
        });
        getContentPane().add(ER);
        ER.setBounds(220, 250, 210, 60);

        Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/USERS.png"))); // NOI18N
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersMouseClicked(evt);
            }
        });
        getContentPane().add(Users);
        Users.setBounds(220, 180, 190, 60);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/LOGOUT.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(510, 30, 112, 50);

        ME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/MANAGE EXAM.png"))); // NOI18N
        ME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEMouseClicked(evt);
            }
        });
        getContentPane().add(ME);
        ME.setBounds(220, 320, 200, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/IMG_20200303_172951.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 240, 420);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/backg5.JPG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 40, 600, 460);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/log2.JPG"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 60, 60);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel5.setText("Exam");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 0, 80, 50);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setText("Snap");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, -10, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 60);

        setSize(new java.awt.Dimension(648, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseClicked
        // TODO add your handling code here:
        verification s = new verification();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsersMouseClicked

    private void ERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ERMouseClicked
        // TODO add your handling code here:
        examResults er = new examResults();
        er.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ERMouseClicked

    private void MEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMouseClicked
        // TODO add your handling code here:
        manage m = new manage();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MEMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        administratorLogin s = new administratorLogin();
        s.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Successfully Logout");
    }//GEN-LAST:event_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ER;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel ME;
    private javax.swing.JLabel Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
