/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hahahahah
 */
public class resultTest extends javax.swing.JFrame {

    /**
     * Creates new form resultTest
     */
    Connection CON = null;
    PreparedStatement PST= null;
    ResultSet RS = null;
    String score1;
    String username;
    String lname;
    String fname;
    int cor = 0;
    public resultTest() {
        initComponents();
        setResizable(false);
        try {
           Connection con = myConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("SELECT * FROM compare");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel tm = (DefaultTableModel)Table1.getModel();
           tm.setRowCount(0);
           
           while(rs.next())
           {
               Object o[] = {rs.getString("No"),rs.getString("value")};
               tm.addRow(o);   
           }
        }catch (Exception e) {
           JOptionPane.showMessageDialog(this, e);
        }
        
        int count = Table1.getRowCount();
        int sc = 0;
        for(int i = 0; i< count; i++){
            String cor = String.valueOf(Table1.getValueAt(i, 1));
            if("CORRECT".equals(cor)){
            sc++;  
        }    
        }score.setText(String.valueOf(sc));
    
        try{
            String submitQuery = "UPDATE `user` SET `Score` = ? WHERE Score IS NULL";
            String scr = score.getText();
            CON = DriverManager.getConnection("jdbc:mysql://localhost/exam","root","");
            PST = CON.prepareStatement(submitQuery);
            PST.setString(1, score.getText());
            PST.executeUpdate();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result");
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(200, 150, 190, 20);

        Table1.setBackground(new java.awt.Color(204, 204, 255));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Question No.", "Answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 180, 210, 123);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESULT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 90, 130, 48);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/LOGOUT1.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(90, 410, 132, 43);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("YOUR SCORE:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 330, 130, 50);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/log2.JPG"))); // NOI18N
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 60, 60);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel6.setText("Exam");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(60, 0, 80, 50);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel9.setText("Snap");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(110, -10, 70, 70);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 610, 60);

        score.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("00");
        score.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        score.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                scoreAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(score);
        score.setBounds(180, 330, 110, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/backg8.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 40, 610, 470);

        setSize(new java.awt.Dimension(598, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scoreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_scoreAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreAncestorAdded

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        signIn s = new signIn();
        s.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
