/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exam;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Students
 */
public class studentLogin extends javax.swing.JFrame {

    /**
     * Creates new form studentLogin
     */
    public studentLogin() {
        initComponents();
        setResizable(false);
       // this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        usernameS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clickHere = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordS = new javax.swing.JPasswordField();
        Submit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Login");
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setText("STUDENT LOGIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 50, 170, 40);

        usernameS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSActionPerformed(evt);
            }
        });
        getContentPane().add(usernameS);
        usernameS.setBounds(340, 150, 190, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel1.setText("USERNAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 120, 80, 30);

        clickHere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/CLICK HERE.png"))); // NOI18N
        clickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickHereMouseClicked(evt);
            }
        });
        getContentPane().add(clickHere);
        clickHere.setBounds(330, 330, 220, 40);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 180, 80, 30);

        passwordS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSActionPerformed(evt);
            }
        });
        getContentPane().add(passwordS);
        passwordS.setBounds(340, 210, 190, 30);

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/LOGIN.png"))); // NOI18N
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(350, 250, 190, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(350, 100, 180, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jLabel2.setText("Don't have an accont?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 310, 140, 30);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/Buttons/BACK.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 340, 60, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/log2.JPG"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 60, 60);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel5.setText("Exam");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 0, 80, 50);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setText("Snap");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, -10, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exam/images/backg3.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 10, 640, 380);

        setSize(new java.awt.Dimension(607, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSActionPerformed

    private void passwordSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String uname = usernameS.getText();
        String pass = String.valueOf(passwordS.getPassword());
        
        String query = "SELECT * FROM `exam` WHERE `USERNAME`=? AND `PASSWORD` =?";
        
        try {
            ps = myConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, uname);
            ps.setString(2, pass);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                student s = new student();
                s.setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null,"Login Error!\nInvalid Username/Password");
            }
        } catch (SQLException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitMouseClicked

    private void clickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickHereMouseClicked
        // TODO add your handling code here:
        registration r = new registration();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickHereMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        signIn s = new signIn();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Submit;
    private javax.swing.JLabel back;
    public javax.swing.JLabel clickHere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField passwordS;
    private javax.swing.JTextField usernameS;
    // End of variables declaration//GEN-END:variables
}
